volumes:
    builder-data: {}

services:
    builder:
        build:
            context: services/php
            target: builder
        init: true
        depends_on:
            - postgres
        environment:
            - MERCURE_URL=http://frontend/.well-known/mercure
            - MERCURE_PUBLISHER_JWT_KEY=!ChangeThisMercureHubJWTSecretKey!
            - MERCURE_PUBLIC_URL=https://${PROJECT_ROOT_DOMAIN}/.well-known/mercure
            - PHP_CS_FIXER_IGNORE_ENV=1
            - COMPOSER_MEMORY_LIMIT=-1
            - GITHUB_ACTIONS
            - UID=${USER_ID}
        volumes:
            - "builder-data:/home/app"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "../..:/var/www:cached"
        profiles:
            - default
